### ISSUE TITLE
Make the PW3 branch the default

### ISSUE THREAD

**Issue by gmclelland** [madebymats/FieldtypeLeafletMapMarker-#10]
Is there any way you could make the PW3 branch the default?  The modules directory still shows 2.8.1 as the latest version of Leaflet Map Marker.

**Comment by mikerockett** [comment]
+9999. Per my issue posted, I didn't even realise there was another branch. It does appear to be stable, so please could you make it default? Thanks.

**Comment by madebymats** [comment]
Sorry forgot to fix this. I changed the PW3 branch to default does that solve this issue?

**Comment by gmclelland** [comment]
Yes, thank you

**Comment by mikerockett** [comment]
Thank you 👍
