### ISSUE TITLE
Maps with a single marker not working with Leaflet 1.2

### ISSUE THREAD

**Issue by mestaritonttu** [madebymats/FieldtypeLeafletMapMarker-#16]
The markers appear in a map with multiple markers, but not in maps with a single marker. The console shows no error.

I added a watcher to line 57 in MarkupLeafletMap.js (this.addMarker = function(lat, lng, url, title, extra) {) and stepped forward. The marker variable stayed blank.

Btw. I also needed to add this script to even get to this point: https://unpkg.com/drmonty-leaflet-awesome-markers@2.0.2/js/leaflet.awesome-markers.js

**Comment by madebymats** [comment]
This seems to be working now.

**Comment by mestaritonttu** [comment]
> This seems to be working now.

How exactly is it working for you? Please copy and paste all the script and CSS includes in your head for a working setup.

I updated the module to the latest, 3.0.3. Single markers still were not showing up with Leaflet 1.2 and the extras from the time of filing the issue. I tried updating all the assets to the latest versions, but it did not help.

Here are my includes:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"></script>
<script src="https://unpkg.com/leaflet-providers@1.4.0/leaflet-providers.js"></script>
<script src="https://unpkg.com/drmonty-leaflet-awesome-markers@2.0.2/js/leaflet.awesome-markers.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $templatesurl?>css/MarkerCluster.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $templatesurl?>css/MarkerCluster.Default.css" />
<script type="text/javascript" src="https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js"></script>
<script type="text/javascript" src="/site/modules/FieldtypeLeafletMapMarker/MarkupLeafletMap.js"></script>
```

**Comment by madebymats** [comment]
$map = wire('modules')->get('MarkupLeafletMap');
//Output this in the html header
$mapCode = $map->getLeafletMapHeaderLines(); 
//Output this in the template
$mapRender = $map->render($page, 'map', array('height' => '500px', 'markerIcon' => 'map-marker')); 

**Make sure you install the Inline script module (Under the mark up modules).**

**Comment by mestaritonttu** [comment]
Inline script is installed as the whole setup was working before trying Leaflet 1.2.
$map->getLeafletMapHeaderLines(); does not render anything for me. var_dumping it gives a blank string.

**Comment by mestaritonttu** [comment]
> Inline script is installed as the whole setup was working before trying Leaflet 1.2.
> $map->getLeafletMapHeaderLines(); does not render anything for me. var_dumping it gives a blank string.

Ok, this was just a blunder related to templates on my part. But the Leaflet.js included is 0.7.7. If I modify the MarkupLeafletMap.module to refer to 1.2.0, it does not render any map. Of course this is probably related to incompatibility with the providers etc.
So you really actually tried with 1.2.0 and got it working? Asking before I try modifying the module more.

**Comment by madebymats** [comment]
I'm using the latest version of the module.

**Comment by mestaritonttu** [comment]
> I'm using the latest version of the module.

I was asking about Leaflet 1.2.0 or newer, not about the PW module. It is what this issue is about. So: have you tested by replacing https://unpkg.com/leaflet@0.7.7/dist/leaflet.js and https://unpkg.com/leaflet@0.7.7/dist/leaflet.css in MarkupLeafletMap.module with 1.2.0 or greater and have everything work?

**Comment by mestaritonttu** [comment]
Ah, now I realised my mistake: I was missing leaflet.awesome-markers.css !! D'oh. Sorry for the noise.
