### ISSUE TITLE
Open popup via link

### ISSUE THREAD

**Issue by connorbrownweb** [madebymats/FieldtypeLeafletMapMarker-#17]
Hello, 

Does anyone know how to open the info window of the marker when a link is clicked? I want to list a bunch of clickable buttons that open the map at different points, basically a 'view on map' button.

Best, 
Connor

**Comment by madebymats** [comment]
This is not in the scope of this module currently. Here is an example how to do it: https://stackoverflow.com/questions/17632359/how-to-open-leaflet-marker-popup-from-link-outside-of-map
