### ISSUE TITLE
Error:  Failed module dependency: InputfieldLeafletMapMarker requires Processwire

### ISSUE THREAD

**Issue by gmclelland** [madebymats/FieldtypeLeafletMapMarker-#6]
Hello,

I'm trying the PW3 branch of this module and while installing this module and even after this module is installed, I'm seeing " Failed module dependency: InputfieldLeafletMapMarker requires Processwire" when I visit the modules page.

Thank you for providing this module.  So far it still seems to work even with the error message.

**Comment by netcarver** [comment]
Thanks for the pull request - now merged. Please close this issue if the merge fixes it.

**Comment by gmclelland** [comment]
Yep, it fixed.  Thank you.
