### ISSUE TITLE
Document changing tile providers on the front end

### ISSUE THREAD

**Issue by gmclelland** [madebymats/FieldtypeLeafletMapMarker-#8]
Just a suggestion:
You might want to document the "provider" option in the README.md

In case anyone else is reading this, I was able to change the front end display tile provider by using the following:

```php
echo $map->render($page, 'cleanup_location', array(
				'height' => '500px',
				'markerLinkField' => '',
				'markerIcon' => 'thumb-tack',
				'provider' => 'OpenStreetMap.BlackAndWhite',
				'markerColour' => 'green',)); ?>
```
This looks like a very useful module.  Thanks again.

**Comment by netcarver** [comment]
Readme file updated in both master and PW3 branches.

Thanks!

**Comment by gmclelland** [comment]
@netcarver or @madebymats - Do you know how to specify providers that require api keys?

https://processwire.com/talk/topic/19292-leaflet-on-github-or-processwire-plugin/ the person is asking how he can use this module with a custom mapbox map that he built at https://api.mapbox.com/styles/v1/papafrancesco/cj8w4kjz08l3x2slhj8c9zmvp.html?fresh=true&title=true&access_token=pk.eyJ1IjoicGFwYWZyYW5jZXNjbyIsImEiOiJjaXFmZDRubzkwMDduaHhuaHVxemk5amZ5In0.cpMeGC7s9Pw8KqKXalh0Wg#7.9/37.789772/13.571864/0

On https://github.com/leaflet-extras/leaflet-providers they [give instructions for Mapbox](https://github.com/leaflet-extras/leaflet-providers#mapbox), but I'm not sure how to specify those options within this module?
